name: Nightly forecast update

on:
  schedule:
    - cron: '30 1 * * *'        # 01:30 UTC every day
  workflow_dispatch:            # lets you trigger it by hand

jobs:
  build-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get update && sudo apt-get install -y libgomp1   # CatBoost needs OpenMP

      - name: Run nightly pipeline
        run: |
          # launch the package as a module so "src" is on PYTHONPATH
          python -m src.pipeline

      - name: Commit & push updated data
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "Wind-Bot"
          git config user.email "actions@github.com"
          git add data/predictions/latest.parquet
          git add data/features/history.parquet
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            ts=$(date -u +'%Y-%m-%d')
            git commit -m "Nightly forecast update: $ts"
            git push
          fi
